[package]
name = "time_bank"
version = "0.1.0"
authors = ["Clayton Herbst <herbsca1@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.5"

[dependencies.rocket_contrib]
version = "0.4.5"
default-features = false
features = ["json", "helmet"]